docs: populated the readme file with project info
PoMaKoM-RSTeam/send-to-telegram-front pull request #11
Opened 2022-01-06 17:36 UTC by AlexXG0152

2022-01-06 17:36 UTC, AlexXG0152 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить README файл](https://trello.com/c/C7N3JFu2/6-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-readme-%D1%84%D0%B0%D0%B9%D0%BB)

2022-01-06 19:34 UTC, gomunkool submitted a review, later dismissed

2022-01-07 00:15 UTC, PoMaKoM commented
Очень нравится. Минорные изменения и вольём

2022-01-07 00:15 UTC, PoMaKoM commented
![image](https://user-images.githubusercontent.com/40242499/148470453-3b8db5d2-d211-4ef4-85c5-89cbb4270038.png)

Это не относится к нашему репозиторию. Лучше всего будет заменить на ссылочку на бек

2022-01-07 00:17 UTC, PoMaKoM commented
Ту мач картинок. Оставлем только эти: 
![image](https://user-images.githubusercontent.com/40242499/148470641-c719842f-ae60-499a-b881-ce7a8b1ad2bb.png)

2022-01-07 00:20 UTC, PoMaKoM requested changes

2022-01-07 00:20 UTC, PoMaKoM commented on README.md
> +![GitHub](https://img.shields.io/github/license/PoMaKoM-RSTeam/send-to-telegram-front?style=for-the-badge)
Уменьшить кол-во

2022-01-07 00:20 UTC, PoMaKoM commented on README.md
> +
Удаляем коммент

2022-01-07 00:20 UTC, PoMaKoM commented on README.md
> + -->
Удаляем все комменты

2022-01-07 00:20 UTC, PoMaKoM commented on README.md
> +-->
+

2022-01-07 00:20 UTC, PoMaKoM commented on README.md
> +npm install -g sendToTelegram
Лож. Такой скрипт не сработает, у нас не пакет.

Возьми скрипты из реакта

2022-01-07 15:48 UTC, PoMaKoM approved these changes

2022-01-07 20:05 UTC, merged