feat: add actions prettier eslint
PoMaKoM-RSTeam/send-to-telegram-front pull request #19
Opened 2022-01-09 17:20 UTC by KaterinaKachann

2022-01-10 07:25 UTC, KaterinaKachann commented
![](https://github.trello.services/images/mini-trello-icon.png) [Создать Actions в репозитории](https://trello.com/c/dZbvvSxB/12-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-actions-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B8)

2022-01-10 18:02 UTC, PoMaKoM commented
1. Поправить конфликты

2022-01-10 20:10 UTC, PoMaKoM requested changes

2022-01-10 20:10 UTC, PoMaKoM commented on .github/workflows/check.yml
> +        run: npx prettier --write ./src
npx prettier --check

2022-01-10 20:10 UTC, PoMaKoM commented on .github/workflows/check.yml
> +        node-version: [15.x]
ноду меняем на 16

2022-01-10 20:10 UTC, PoMaKoM commented on .github/workflows/check.yml
> +
Заменить на

```
on:
  pull_request:
    branches:
      - "develop"
```

2022-01-10 20:23 UTC, PoMaKoM commented on .github/workflows/check.yml
> +        run: npx prettier --write ./src
--write выполняет изменения файла. А в гит экшонах мы только делаем проверку

2022-01-11 17:07 UTC, gomunkool submitted a review, later dismissed

2022-01-11 21:01 UTC, PoMaKoM approved these changes

2022-01-11 21:02 UTC, merged