refactor: refactor sass and add libraries
PoMaKoM-RSTeam/send-to-telegram-front pull request #25
Opened 2022-01-17 12:00 UTC by KaterinaKachann

2022-01-17 12:02 UTC, KaterinaKachann commented
![](https://github.trello.services/images/mini-trello-icon.png) [SASS in React not import (from)](https://trello.com/c/vqdaXP0Q/29-sass-in-react-not-import-from)

2022-01-18 16:09 UTC, gomunkool submitted a review, later dismissed

2022-01-18 18:32 UTC, PoMaKoM requested changes

2022-01-18 18:32 UTC, PoMaKoM commented on package.json
> +    "node-scss": "sass --watch src/scss/style.scss public/style.css"
Убрать

2022-01-18 18:32 UTC, PoMaKoM commented on package.json
> +    "scss-loader": "^0.0.1",
Убрать

2022-01-18 18:32 UTC, PoMaKoM commented on public/index.html
> +    <link rel="stylesheet" href="./style.css" />
Убрать

2022-01-18 21:00 UTC, PoMaKoM approved these changes

2022-01-18 21:00 UTC, merged