Feature/fr 27
PoMaKoM-RSTeam/send-to-telegram-front pull request #30
Opened 2022-01-26 19:24 UTC by Archi-Minsk

2022-01-26 20:09 UTC, Archi-Minsk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Удалить всё, что связано с тестами](https://trello.com/c/KxCpTsxK/22-%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D0%B2%D1%81%D1%91-%D1%87%D1%82%D0%BE-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BE-%D1%81-%D1%82%D0%B5%D1%81%D1%82%D0%B0%D0%BC%D0%B8)

2022-01-26 20:09 UTC, Archi-Minsk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать каркас страницы Модерации (страница ролей)](https://trello.com/c/QNkVKds9/27-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BA%D0%B0%D1%80%D0%BA%D0%B0%D1%81-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%BC%D0%BE%D0%B4%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%80%D0%BE%D0%BB%D0%B5%D0%B9)

2022-01-26 20:39 UTC, gomunkool commented
Я бы батоны в отдельный компонент вынес. Классы не по БЭМУ. А так хз, я пока по коду не вижу прям норм или как.

2022-01-26 20:42 UTC, gomunkool commented
И ещё у тебя какой-то красный крест стоит на ПР, я хз, что это? Можно ли с ним апрув кидать я не знаю.

2022-01-26 22:09 UTC, PoMaKoM commented
Название ветки неверное

2022-01-26 22:11 UTC, PoMaKoM commented
> И ещё у тебя какой-то красный крест стоит на ПР, я хз, что это? Можно ли с ним апрув кидать я не знаю.

Это проверка сборки. GithubActions. Если крестик, то есть ошибки. Открываем тут и фиксим.
![image](https://user-images.githubusercontent.com/40242499/151255542-eac2f1e0-37dd-4a1a-bc43-a61fafb795bd.png)

Апрув ставить можно, но пр не зайдет.

2022-01-26 22:12 UTC, PoMaKoM commented
> Я бы батоны в отдельный компонент вынес. Классы не по БЭМУ. А так хз, я пока по коду не вижу прям норм или как.

Мы не пишем классы по БЭМу. Можно, но не нужно на самом деле

2022-01-26 22:13 UTC, PoMaKoM requested changes

2022-01-26 22:13 UTC, PoMaKoM commented on src/pages/Moderation/Moderation.tsx
> +        <span className='span-#' />
Название класса странное

2022-01-27 15:28 UTC, KaterinaKachann approved these changes, later dismissed
Конфликты с App.tsx

2022-01-28 10:37 UTC, gomunkool submitted a review, later dismissed

2022-01-28 10:37 UTC, gomunkool commented on .vscode/settings.json
> +}
Не понятно, что за кирпич и почему на русском?

2022-02-01 12:10 UTC, PoMaKoM requested changes

2022-02-01 12:10 UTC, PoMaKoM commented on .vscode/settings.json
> +}
.vscode папка должна быть в гит игнор. Если её нет, то добавить

2022-02-01 12:10 UTC, PoMaKoM commented
Конфликты с App.tsx

2022-02-01 20:00 UTC, PoMaKoM approved these changes

2022-02-01 20:00 UTC, merged