feat: add setting change theme
PoMaKoM-RSTeam/send-to-telegram-front pull request #38
Opened 2022-02-16 21:09 UTC by KaterinaKachann

Добавлена настройка смены темы с черной на белую

2022-02-16 21:13 UTC, KaterinaKachann commented
![](https://github.trello.services/images/mini-trello-icon.png) [Смена темы приложения](https://trello.com/c/am3duKf0/46-%D1%81%D0%BC%D0%B5%D0%BD%D0%B0-%D1%82%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F)

2022-02-17 11:25 UTC, PoMaKoM commented on public/index.html
> -    <noscript>You need to enable JavaScript to run this app.</noscript>
Зачем это удалила?

Это необходимая строка

2022-02-17 11:25 UTC, gomunkool approved these changes, later dismissed
Очень всё красиво

2022-02-17 11:25 UTC, gomunkool commented on src/Pages/LoginPage/LoginPage.scss
> +        // color: #222;
комент, можно убрать

2022-02-17 11:25 UTC, PoMaKoM commented on public/index.html
> +    <noscript id="inject-styles-here"></noscript>
Либо перенеси сюда текст

2022-02-17 11:26 UTC, PoMaKoM requested changes

2022-02-17 11:26 UTC, PoMaKoM commented on public/index.html
> +    <noscript id="inject-styles-here"></noscript>
И зачем тут ID ?

2022-02-17 13:06 UTC, PoMaKoM approved these changes

2022-02-17 13:06 UTC, PoMaKoM commented on src/Pages/LoginPage/LoginPage.scss
> +        // color: #222;
+

2022-02-17 13:06 UTC, PoMaKoM commented on src/Pages/SettingsPage/SettingsPage.scss
> +  // font-size: 60px;
Убрать коммент

2022-02-17 13:06 UTC, PoMaKoM commented on src/Pages/StatisticsPage/StatisticsPage.scss
> +  // color: #333;
Убрать коммент

2022-02-17 13:06 UTC, merged